### ISSUE TITLE
Missing xmls in the data

### ISSUE THREAD

**Issue by LamaNIkesh** [tianheyu927/mil#11]
Hi,

It seems like this problem has been already marked as closed but the texture folder is missing xmls. I first unzipped it manually just to check if xmls are present in the textures folder but I only see pngs. 

Is the zipped dataset missing xmls or am I doing something wrong?

Thanks,
Nikesh

**Comment by ngalym** [comment]
The same issue here. It was there once when I downloaded, and now it is missing again.

**Comment by tianheyu927** [comment]
As mentioned in the README, the xmls can be found [here](https://github.com/tianheyu927/gym/tree/mil/gym/envs/mujoco/assets).
