### ISSUE TITLE
Problem running run_sim_push_video_only.sh

### ISSUE THREAD

**Issue by ngalym** [tianheyu927/mil#12]
The scripts 'run_sim_push.sh' and 'run_sim_vision_reach.sh' (given in the script directory data/sim_vision_reach_noisy does not exist, changed into data/sim_vision_reach) were run successfully, however the run_sim_push_video_only.sh doesn't give the model with action (judging from the saved model's folder name no_action.zero_state.).
`Saving model to: /tmp/data/sim_push.xavier_init.4_conv.4_strides.16_filters.3_fc.200_dim.bt_dim_20.mbs_3.ubs_1.numstep_1.updatelr_0.01.clip_10.conv_bt.fp.no_action.zero_state.two_heads.1d_conv_act_3_32_10x1_filters/model_nnn
./scripts/run_sim_push_video_only.sh: line 8: --temporal_num_layers=3: command not found
`
Previously suggested solution to use tf version 1.4 didn't solve the problem.

**Comment by tianheyu927** [comment]
`run_sim_push_video_only.sh` is running the algorithm with just videos as the input, without action labels and state input. Hence the model's folder is named as 'no_action.zero_state'.
