### ISSUE TITLE
I can't find the gym env "ReacherMILTest-v1"

### ISSUE THREAD

**Issue by superggb** [tianheyu927/mil#16]
I have installed mujoco,mujoco_py,gym successfully.But when I test the reach script, I can't find the gym env "ReacherMILTest-v1" anymore.

It seems like a self-build environment, so can anyone tell me how can I use the gym env?

**Comment by tianheyu927** [comment]
Are you using my fork of gym as mentioned in the README?

> First clone the fork of the gym repo found here, and following the instructions there to install gym. Switch to branch mil.

**Comment by superggb** [comment]
I'm sure I used the fork gym.
after git clone your gym, I use pip install -e '.[all]' .
I think I can find the"ReacherMILTest-v1' in /gym/env/__init__.py if it exits. 
But I can't find it anymore, so I cannot use gym.make("ReacherMILTest-v1") successfully.
