### ISSUE TITLE
low success rate

### ISSUE THREAD

**Issue by ZiyeHu** [tianheyu927/mil#18]
I suspect there is something wrong with the code.
I ran your code according your instructions,and tested in test_sim_vision_reach.sh but the final success rate is just around 10%.

**Comment by daiyk** [comment]
Hi, I have a separate question since you run it successfully. Which type of GPU are you using? I have GTX1080 (8GB) but the model just use up my memory and explode it. Did you use a better GPU with bigger memory? Thank you

**Comment by ZiyeHu** [comment]
1080Ti. I have encountered this problem when I tried to run the "push" task , but I can run the "reach" task sucessfully. But I found there's  a serious problem with the code：the environments of the "reach"  test demos  are exactly the same with the gym environments, it means that the  gym environments know the results(states and actions) in advance. in other words, the results maybe directly come from the "reach"  test demos.

在2019-10-29 22:31:05，daiyknotifications@github.com写道：

Hi, I have a separate question since you run it successfully. Which type of GPU are you using? I have GTX1080 (8GB) but the model just use up my memory and explode it. Did you use a better GPU with bigger memory? Thank you

**Comment by daiyk** [comment]
> 1080Ti. I have encountered this problem when I tried to run the "push" task , but I can run the "reach" task sucessfully. But I found there's a serious problem with the code：the environments of the "reach" test demos are exactly the same with the gym environments, it means that the gym environments know the results(states and actions) in advance. in other words, the results maybe directly come from the "reach" test demos. 在2019-10-29 22:31:05，daiyknotifications@github.com写道： Hi, I have a separate question since you run it successfully. Which type of GPU are you using? I have GTX1080 (8GB) but the model just use up my memory and explode it. Did you use a better GPU with bigger memory? Thank you — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks! I will check the code too.

**Comment by ZiyeHu** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by ZiyeHu** [comment]
div.fox_html_content { line-height: 1.5;}
      /* 一些默认样式 */
      blockquote { margin-Top: 0px; margin-Bottom: 0px; margin-Left: 0.5em }
      ol, ul { margin-Top: 0px; margin-Bottom: 0px; list-style-position: inside; }
      p { margin-Top: 0px; margin-Bottom: 0px }
    


 

  
  
    reply.github.com 密码通知!你好, ***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
      reply.github.com 密码通知。 © 2022

**Comment by ZiyeHu** [comment]
关于<藤穿发蹬峻>2<蔼诫鲍凳箭忽纭绎剿肆>0<泓昔在决介炉染>2<爱好出勤奋，勤奋出天才。>2年<祭蕴匙桢扫>个人劳<既然所有我的歌和我的赞美>动补<桃花落>助（补<路遥归梦难成>贴）通<愁一箭风快>知，<选择朋友要慢，换朋友要更慢。>详<桃花落>情请<饭后百步走，活到九十九。>及<腾不出时间娱乐，早晚会被迫腾出时间生病。>时查收<哑巴吃黄连有苦说不出>附<一片神鸦社鼓>件！<艰抗吗赐雁>
