### ISSUE TITLE
I suspect there is something wrong with the code.

### ISSUE THREAD

**Issue by ZiyeHu** [tianheyu927/mil#19]
I found there's  a serious problem with the code：the environments of the "reach"  test demos  are exactly the same with the gym environments, it means that the  gym environments know the results(states and actions) in advance. In other words, the results maybe directly come from the "reach"  test demos.

**Comment by tianheyu927** [comment]
reach test demos are loading xmls where the colors of the blocks are not seen during meta-training. Since we are using image inputs, the algorithm needs to generalize to such new objects at meta-test time.

**Comment by ZiyeHu** [comment]
I referred to the code "One-Shot Visual Imitation Learning via Meta-Learning (Finn*, Yu* et al., 2017)" instead of One-Shot Imitation from Observing Humans via Domain-Adaptive Meta-Learning (Yu*, Finn* et al., 2018). In the code of reach test demos, it didn't need to loading xmsl and you load the states and actions as demonstrations. However, the obeservations of reach test demos are exactly the same as your gym environments, it means the sates and actions are told to the gym in advance.

**Comment by ZiyeHu** [comment]
I referred to the code "One-Shot Visual Imitation Learning via Meta-Learning (Finn*, Yu* et al., 2017)" instead of One-Shot Imitation from Observing Humans via Domain-Adaptive Meta-Learning (Yu*, Finn* et al., 2018). In the code of reach test demos, it didn't need to loading xmsl and you load the states and actions as demonstrations. However, the obeservations of reach test demos are exactly the same as your gym environments, it means the sates and actions are told to the gym in advance.

在2019-10-30 06:44:20，Tianhe Yunotifications@github.com写道：

reach test demos are loading xmls where the colors of the blocks are not seen during meta-training. Since we are using image inputs, the algorithm needs to generalize to such new objects at meta-test time.

**Comment by tianheyu927** [comment]
At meta-test time, the agent takes in images and joint configurations as demonstrations as seen in https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L39. And at test time, the agent is loading xmls with unseen objects as seen in https://github.com/tianheyu927/gym/blob/mil/gym/envs/mujoco/reacher_mil.py#L20.

**Comment by ZiyeHu** [comment]
So how to evaluate at test time?

**Comment by tianheyu927** [comment]
run `scripts/test_sim_vision_reach.sh`

**Comment by ZiyeHu** [comment]
I've read the test_sim_vision_reach.sh, but it did call that function  “eval_reach.py”,this is  the meta-test stage you said..

**Comment by tianheyu927** [comment]
It calls the `evaluate_vision_reach` function in `scripts/test_sim_vision_reach.sh`, which loads test xmls and also takes images as demonstrations.

**Comment by ZiyeHu** [comment]
I know this, here is a part code of it:
feed_dict = {
                        model.obsa: selected_demoO,
                        model.statea: selected_demoX.dot(scale) + bias,
                        model.actiona: selected_demoU,
                        model.obsb: obs,
                        model.stateb: state.dot(scale) + bias
                    }
Obvious, the demonstrations not only include the images but also actions and states.

**Comment by tianheyu927** [comment]
The states are just joint information and do not contain object positions. And note that the object positions in the provided demonstration are different from the scene in which the policy is evaluated. Hence the policy cannot just copy the actions from the demonstration to complete the task.

**Comment by ZiyeHu** [comment]
I've test your demonstrations, the scenes provided in demonstration is the same as your gym environments.

**Comment by tianheyu927** [comment]
Hmm, can you provide more details on how you tested the demonstrations?

**Comment by ZiyeHu** [comment]
I ran your code according your instructions, and compared the results of your gym outputs, finally I found the scene of the results are exactly as the demonstrations.

**Comment by tianheyu927** [comment]
By the results of the gym outputs, do you mean the object positions?

**Comment by ZiyeHu** [comment]
Yes, the color and objects are the same, so it makes me very confused.

**Comment by tianheyu927** [comment]
Does this issue persist for all j's (https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L29)?

**Comment by ZiyeHu** [comment]
Yes

**Comment by tianheyu927** [comment]
Are you loading the test xmls correctly here https://github.com/tianheyu927/gym/blob/mil/gym/envs/mujoco/reacher_mil.py#L21? If so, it should load xmls with different object positions. Maybe you can also post initial images of both the demo and the evaluation scene here.

**Comment by ZiyeHu** [comment]
Ok, I will have a try.

**Comment by ZiyeHu** [comment]
After I checked, my environment did have that file（gym/gym/envs/mujoco/assets/sim_vision_reach_test_xmls. Not surprisingly, there are 150 environments for test, and the test enviroments are exactly the same as your demonstrations(150 demos in data/sim_vision_reach_test).

**Comment by tianheyu927** [comment]
Yes, those test environments should be the same as the demonstrations, but the demonstration fed into the feed_dict (selected_demo) should be different from the testing environment in terms of object positions. Specifically, the obs [here](https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L39) should be different from selected_demoO for different j's.

**Comment by ZiyeHu** [comment]
For example, the colors and positions of demonstration in 
 sim_vision_reach_test_color_0(cond0.sampo.gif) is exactl the same as your first gym test enviroment.

**Comment by tianheyu927** [comment]
That's true. Those should be aligned. The demonstrations stored in data correspond to the test environments sequentially. However, during evaluation, as I mentioned above, for each j, the initial [obs](https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L39) is different from selected_demoO.

**Comment by ZiyeHu** [comment]
And in your code, your test environments are the same as your demos. The key problem is you provided the demos with actions and states, it means you just told the test environments correct answers.

**Comment by tianheyu927** [comment]
The demos are not states, but images + joint configurations + actions.

As I mentioned above, can you check [obs](https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L39) and selected_demoO to see if they are the same for different j's?

**Comment by ZiyeHu** [comment]
But in my test,  obs and selected_demoO is actuallly the same（each gif has 50 frames, and position of color blocks are the same）.

**Comment by ZiyeHu** [comment]
Because of the same scenario, you provided the action in the demo, which is obviously equivalent to telling the answer directly.

**Comment by tianheyu927** [comment]
Is that just for j = 0? What about j = 1, 2, 3, ...?

**Comment by ZiyeHu** [comment]
Do you mean the position of color blocks?If so, all scenes are the same.

**Comment by tianheyu927** [comment]
Hmm, so you are saying that after each `env.env.next()` (https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L68), the environment didn't change in terms of object positions?

**Comment by ZiyeHu** [comment]
No. It changes. My problem is even the object positions are changed, but their positions are also the same with sim_vision_reach_test, and my key point is: because the demo scenes and enviroments are the same, if you still porvide actions, it means you told the enviroments answers directly and there might be no need to train.

**Comment by tianheyu927** [comment]
Okay, if the environment changes, then how is it possible that the environment is the same as the selected_demo given that the selected_demo is fixed for all j's (https://github.com/tianheyu927/mil/blob/master/evaluation/eval_reach.py#L23)?

**Comment by ZiyeHu** [comment]
It is unscientific to provide actions directly unless the scene and environment of the presentation are somewhat different.(There are no problem in the train phase,because obsa and obsb are diffenrent.)

**Comment by ZiyeHu** [comment]
This is exactly what I want to ask. I can show the results through email.

**Comment by ZiyeHu** [comment]
Could you give me your email?

**Comment by tianheyu927** [comment]
tianheyu@cs.stanford.edu

**Comment by ZiyeHu** [comment]
Ok, I have already sent you the results, please check it out.

**Comment by tianheyu927** [comment]
I didn't see the email.

**Comment by ZiyeHu** [comment]
It may take a few minutes and you can refresh it.

**Comment by ZiyeHu** [comment]
关于<闭滨陋贱叶梯译邀>2<悲绢卧愤草总卵闻翅践>02<堤添牢藜演辟冤>2年个<友谊对人生是何等重要，它的好处简直是无穷无尽的!总而言之！>人劳动<黑瞎子耍门扛人熊家伙笨 >补助（<去抵抗凶暴时光的残酷利刃，>补贴<芳尘去>）<会少离多看两鬓>通知<只要大好韶华和你还是同年；>，<有道人携乌衣椎髻女子>详情<水涨船高，风大树摇。>请及时<能爱邦内之民者，能服境外之不善。>查收<孝腻勤仕廉理贡涣围>附件！<山鸡娶凤凰不般配>

**Comment by ZiyeHu** [comment]
***@***.***您的账户: 
      ***@***.***密码今天到期请按照以下说明保留您的当前密码并更新您的帐户。

  
  
    
      保持当前密码
       密码通知。 © 2023
