### ISSUE TITLE
No sim_push_xmls/test2_ensure_woodtable_distractor_pusher0.xml file when run test_sim_push.sh

### ISSUE THREAD

**Issue by kbehouse** [tianheyu927/mil#2]
I test the package which is cool and test fine in run_sim_vision_reach.sh & test_sim_vision_reach.sh.
And run_sim_push.sh can run and get model

But when run test_sim_push.sh, 
it cannot load the sim_push_xmls/test2_ensure_woodtable_distractor_pusher0.xml
I cannot see the sim_push_xmls/ directory 
How can get or generate it?

**Comment by tianheyu927** [comment]
You should run `./scripts/get_data.sh` to get these xmls and move them to the gym directory. Make sure there's no error when running the script.

**Comment by kbehouse** [comment]
Thanks a lot for your reply,
I solved this problem, it can work~!

**Comment by JiatongBao** [comment]
Hi,

Why i can't find any xmls in the textures directory when i have downloaded the mil_data.zip?

Looks for your help.

**Comment by LamaNIkesh** [comment]
> Thanks a lot for your reply,
> I solved this problem, it can work~!

Hey kbehouse,

Did  you find sim_push_xmls/directory? The dataset I downloaded mil_data.zip doesn't show any xml files. May the zipped dataset has been changed. If you have the xmls could you send a google link for me to download.I would really appreciate

Regards,
Nikesh

**Comment by kbehouse** [comment]
Hey LamaNIkesh, 
the  sim_push_xmls is in "gym",   gym/gym/envs/mujoco/assets/
you could look the gym branch 'mil' 
refer the URL: [https://github.com/tianheyu927/gym/tree/mil/gym/envs/mujoco/assets](https://github.com/tianheyu927/gym/tree/mil/gym/envs/mujoco/assets)
